### ISSUE TITLE
Error when using that in static methods.

### ISSUE THREAD

**Issue by ketronix-dev** [rstm-sf/JsonRepairUtils#14]
![image](https://github.com/rstm-sf/JsonRepairUtils/assets/111521698/7b8a2e02-3e27-439c-a8fa-e3f141dcce5f)

**Comment by rstm-sf** [comment]
Hello, you need to create an instance.

```c#
var jsonRepair = new JsonRepair();
var repaired = jsonRepair.Repair(json);
```

**Comment by ketronix-dev** [comment]
Okay, but that doesnt work, method returns null
![image](https://github.com/rstm-sf/JsonRepairUtils/assets/111521698/ad511cd6-91ea-4e57-919c-0c42376d461e)

If you want to try this JSON, take from [there](https://cist.nure.ua/ias/app/tt/P_API_PODR_JSON)

**Comment by rstm-sf** [comment]
Could you please create a new issue with clarify and attach the file?
